### PR TITLE
Form names changed and user variables added

### PR DESCRIPTION
**Pull request by NicolasGraph**
Form names changed to ‘type.name.ext’ (see theme discussions on the forum) and user variables added to replace adi_variables and manage theme prefs.

### CODE REVIEW

**Comment by gocom** [comment]
- I won't implemented form type change; breaks backwards compatibility and they are optional anyway. I personally have never used the type myself even.
- ...and to make management easier I'll be adding recursion support, which makes the management factor moot.
- Variable loading would be better left to other plugin that reads them from preferences, but I could potentially add it, since they are just glorified preferences.

**Comment by NicolasGraph** [comment]
Since this pull request I changed or added more things; let me try to remember:

**Plugin**

- Preferences:
  - [Updated](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=PREF_PLUGIN): Uses Txp 4.6 `PREF_PLUGIN` instead of `PREF_ADVANCED` if possible;
  - [Added](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=oui_flat_upload_levels): I added a plugin pref to choose the production status to use for automatically import files (test, debug, or both). I did it because I was tired to see rah_flat pollute my runtime on testing.
- Uninstall:
  - [Improved?](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=%24this-%3Edeleting): Avoid files loading on plugin deletion. I still need to remember when it was a problem…

**Imports**

- Preferences:
  - [Improved](https://github.com/NicolasGraph/oui_flat/blob/3ad73e7c55638be4c861ed62f336b09ca13c2470/src/Rah/Flat/Import/Prefs.php#L55): You can only change their values to avoid bad things;
  - [Improved](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=20): If set via flat files they are hidden from the Preferences admin tab to avoid any confusion. They come back to normal if removed or if the plugin is disable.
- Forms:
  - [Changed](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=forms): They are stored in subfolders named by types (custom types can be used);
  - [Improved](https://github.com/NicolasGraph/oui_flat/blob/3ad73e7c55638be4c861ed62f336b09ca13c2470/src/Rah/Flat.php#L141): Any custom type name is changed to _misc_ if the plugin is disable too avoid Textpattern to through an error.
- Variables:
  - [Added](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=variables): Support added mainly for theme/user preferences. It replaces adi_variables (which uses a form) by using variables as custom preferences.
- Textpack:
  - [Added](https://github.com/NicolasGraph/oui_flat/search?utf8=%E2%9C%93&q=textpacks): support added.

That's it I think. Let me know if and how I can help; I unfortunatly don't have dedicated commits for all previous changes. I tagged as _Improved_ changes that could, in my mind, improve the original plugin, but the way I did them could probably be improved itself… Thanks for your forgiveness! ;-)

**Comment by gocom** [comment]
Thanks. Altho, I'm not sure if and what I'm going to add. I don't really do the whole design-by-community stuff at all (which from where the feature-ideas probably came from); I want to eat something a chef (and their prep) cooked, not something made by a bunch of knife swinging maniacs. But that said a lot of that is useful feature-wise.

> Improved?: Avoid files loading on plugin deletion. I still need to remember when it was a problem…

There is a disclaimer notice in my readme; the code is experimental. The issue comes from the fact that the importers are initialized within the constructor that is invoked on runtime; as such, importers are also ran when plugin is loaded on uninstall (which it is due to uninstaller callbacks). Importers should be either run on a callback (probably not possible; it'll end up running too late), or the block wrapped in event check.

> Improved: If set via flat files they are hidden from the Preferences admin tab to avoid any confusion. They come back to normal if removed or if the plugin is disable.

Btw, that will set any originally hidden preferences visible on uninstall. If you would wish to do it by altering the DB record, a better way would be to alter the group/event name by prefixing it with unique identifier (`pfx_hippie_` etc). No privs, no sight.

> Improved: You can only change their values to avoid bad things;

Originally rah_flat was supposed to be able to also add preferences (i.e. to allow key-value storage). But I wanted to simplify the code (reduced 15 lines or so) and that fucked up safe_upsert() Textpattern comes with probably doesn't work properly for prefs table. Or something.

Preferences were also supposed to be able to support multiple data format (flat txt files, json), but I removed it to reduce amount of code (5 lines or so).

> Changed: They are stored in subfolders named by types (custom types can be used);

In rah_flat types are optional, and the files are read recursively. I.e. `/templates/forms/sponsors/trunkclub.html` is a valid location. In my opinion you shouldn't use the type at all; I don't.

The only one that does something is the article type. Tho, I could match the parent directory to a predefined list of form types (Textpattern did have a function for that too if I remember right, but at least in 4.5 it was within a panel's source file - if I remember correctly).

> Textpack

If I were to add that, it would use the textpack importer. More readable format, support for language files etc. If the importers work and are still in core (I wrote one, right?).

> Added: Support added mainly for theme/user preferences. It replaces adi_variables (which uses a form) by using variables as custom preferences.

That could very well be separate plugin; rah_flat can import whatever you want to the preference panel; if it were to be able to insert stuff. Tho having them automatically map to correct preference keys without having to specify the prefix is neater looking.

**Comment by NicolasGraph** [comment]
> Thanks. Altho, I'm not sure if and what I'm going to add. I don't really do the whole design-by-community stuff at all (which from where the feature-ideas probably came from)…

Take what you like; I mainly made that by my own while more about PHP and the Txp core.
I was looking for a way to replace adi_variables and then I tried to do something to easily install public themes. But I know that both themes and flat files management (including flat content) were discribed as future core features, so I'm not sure how this plugin will be useful in the next Txp releases.

> Btw, that will set any originally hidden preferences visible on uninstall.

It doesn't, because when hidding these prefs I just prepend 2 before their existing types (any type >= 2 is hidden), keeping a way to know which ones are altered and what is the original type to restore. 

> If I were to add [textpacks], it would use the textpack importer. More readable format, support for language files etc. If the importers work and are still in core (I wrote one, right?).

Yes I thought that there was better way but I still need to explore the core… 

> Tho having [variables] automatically map to correct preference keys without having to specify the prefix is neater looking.

In oui_flat the prefix is added by the plugin on import to recognized them as they are not necessarily grouped together.

**Comment by gocom** [comment]
> Take what you like; I mainly made that by my own while more about PHP and the Txp core.
I was looking for a way to replace adi_variables and then I tried to do something to easily install public themes.

Personally I've always been adding custom preference fields on per project basis; But having a plugin to automatically create them is better.

I wonder what would be the best way to describe which field type it should appear as; i.e. so that the client (or end-user) can later on modify the value through the GUI. I wonder if simple newline check could be used to determinate whether it needs to be a textarea or an input.

If textpacks are supported, translations for the label can be provided through that at least.

> But I know that both themes and flat files management (including flat content) were discribed as future core features, so I'm not sure how this plugin will be useful in the next Txp releases.

Yeah, I saw that. Hopefully it does happen. I mean, it could then work without any type of importing. Heck, you could then install themes through Composer very easily too.

The core probably won't include preference strings, nor variables, so there probably has to be some sort of plugin that extends the data-type support.

> It doesn't, because when hidding these prefs I just prepend 2 before their existing types (any type >= 2 is hidden), keeping a way to know which ones are altered and what is the original type to restore.

Oh yeah. You've two update statements there, and the core explicitly defines the values when selecting the rows. You probably could combine the statements by doing `type=type+20` and `type=type-20 where type >= 20`. Flipping the values to negative might work too, and might be more future compatible.

**Comment by NicolasGraph** [comment]
> I wonder what would be the best way to describe which field type it should appear as; i.e. so that the client (or end-user) can later on modify the value through the GUI. I wonder if simple newline check could be used to determinate whether it needs to be a textarea or an input.

Maybe we should be able to provide [more data](https://github.com/NicolasGraph/oui_flat#variables) for these variables to be able to customize their display.
Otherwise, if we just provide a value, as for prefs, I was wondering if it could be possible to have only one file where each line is a variable or pref… It overhelmed me but you could have an idea.

> If textpacks are supported, translations for the label can be provided through that at least.

Definitely

> You probably could combine the statements by doing type=type+20 and type=type-20 where type >= 20.

Good catch!

> Flipping the values to negative might work too, and might be more future compatible.

Ok, I didn't know that.

Your last commits seem to be great with some cleanest code that what I suggested; I wait, learn and I will see if we oui_flat still has a reason to be updated in few days or weeks.

**Comment by jools-r** [comment]
Good work you guys! The addition of site-specific prefs as variables (replacing adi_variables) with different form types was a big plus. It would great if that could be retained. I like the recursive folder option too. I agree that the article type still has relevance for per-article form switching via the UI.

**Comment by NicolasGraph** [comment]
Txp 4.7 will introduce a public themes support (partly based on your work) which would require a complete rework of the plugin.

**Pull request closed without merging**
